### ISSUE TITLE
Incorrect parsing for plist files with empty <string></string> values

### ISSUE THREAD

**Issue by antoinevg** [wollardj/node-simple-plist#12] opened 2017-03-28 11:19 UTC
If you have a plist file with an empty `<string></string>` value like this:

```
<plist version="1.0">
    <dict>
        <key>DTPlatformBuild</key>
        <string></string>
        <key>DTPlatformName</key>
        <string>iphonesimulator</string>
        <key>DTPlatformVersion</key>
        <string>10.0</string>
    </dict>
</plist>

```

The parser will ignore it and interpret the next key as the value, giving an output like this:

    {
        "DTPlatformBuild":"DTPlatformName",
        "iphonesimulator":"DTPlatformVersion",
        "10.0": ...
    }

* This only affects reading plain-text XML plist files. 
* When reading binary encoded plist files the problem does not appear.
* Writing both text and binary plist files appears to be fine.

**Comment by cmaart** [comment] 2017-03-30 06:57
+1

**Comment by mroswald** [comment] 2017-04-20 18:56
+1

**Comment by wollardj** [comment] 2017-04-26 12:59
This package basically just provides a (hopefully) simple API around three other packages; bplist-parser, bplist-creator, and plist. Since it's only applicable to plain text documents, I'd be willing to bet the issue is related to https://github.com/TooTallNate/plist.js/issues/79 (@cmaart already commented there as well). There's also a PR that claims to resolve the issue here: https://github.com/akofman/plist.js/commit/4163d73f148fd1efffc06366729202c3c7b65184

I'm going to close this out for now, but feel free to continue the discussion here for future readers if you wish.

**Closed by wollardj** 2017-04-26 12:59 UTC
